version: 1

sources:
  - name: thelook
    schema: thelook_ecommerce
    
    # Descriptions get rendered as part of dbt's generated documentation site
    description: >
      This source contains information about the e-commerce website
      The Look. It is a fictional website that sells clothing and
      accessories.

    # dbt can optionally snapshot the "freshness" of the data in your source tables. 
    # This is useful for understanding if your data pipelines are in a healthy state, 
    # and is a critical component of defining SLAs for your warehouse.
    freshness: # default freshness
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    loaded_at_field: _etl_loaded_at

    tables:
      - name: distribution_centers
        description: >
          This table contains information about the distribution centers that
          ship products to customers.
        columns:
          - name: id
            data_type: INT64
          - name: name
            data_type: STRING
          - name: latitude
            data_type: FLOAT64
          - name: longitude
            data_type: FLOAT64

      - name: events
        description: >
          This table contains information about events that users perform on the
          website.
        columns:
          - name: id
            data_type: INT64
          - name: user_id
            data_type: INT64
          - name: sequence_number
            data_type: INT64
          - name: session_id
            data_type: STRING
          - name: created_at
            data_type: TIMESTAMP
          - name: ip_address
            data_type: STRING
          - name: city
            data_type: STRING
          - name: state
            data_type: STRING
          - name: postal_code
            data_type: STRING
          - name: browser
            data_type: STRING
          - name: traffic_source
            data_type: STRING
          - name: uri
            data_type: STRING
          - name: event_type
            data_type: STRING
            description: >
              The type of event that occurred. These include "cart", "home", 
              "cancel", "product", "purchase", and "department".

      - name: inventory_items
        columns:
          - name: id
            data_type: INT64
          - name: product_id
            data_type: INT64
          - name: created_at
            data_type: TIMESTAMP
          - name: sold_at
            data_type: TIMESTAMP
          - name: cost
            data_type: FLOAT64
          - name: product_category
            data_type: STRING
          - name: product_name
            data_type: STRING
          - name: product_brand
            data_type: STRING
          - name: product_retail_price
            data_type: FLOAT64
          - name: product_department
            data_type: STRING
          - name: product_sku
            data_type: STRING
          - name: product_distribution_center_id
            data_type: INT64

      - name: order_items
        columns:
          - name: id
            data_type: INT64
          - name: order_id
            data_type: INT64
          - name: user_id
            data_type: INT64
          - name: product_id
            data_type: INT64
          - name: inventory_item_id
            data_type: INT64
          - name: status
            data_type: STRING
          - name: created_at
            data_type: TIMESTAMP
          - name: shipped_at
            data_type: TIMESTAMP
          - name: delivered_at
            data_type: TIMESTAMP
          - name: returned_at
            data_type: TIMESTAMP
          - name: sale_price
            data_type: FLOAT64

      - name: orders
        columns:
          - name: order_id
            data_type: INT64
          - name: user_id
            data_type: INT64
          - name: status
            data_type: STRING
          - name: gender
            data_type: STRING
          - name: created_at
            data_type: TIMESTAMP
          - name: returned_at
            data_type: TIMESTAMP
          - name: shipped_at
            data_type: TIMESTAMP
          - name: delivered_at
            data_type: TIMESTAMP
          - name: num_of_item
            data_type: INT64

      - name: products
        description: >
          This table contains information about the products that are sold on
          the website.
        columns:
          - name: id
            data_type: INT64
          - name: cost
            data_type: FLOAT64
          - name: category
            data_type: STRING
            description: >
              The category of the product. There are 9 categories that include 
              "Swim", "Jeans", "Pants", "Socks", and "Active", "Shorts", "Sweaters", 
              "Underwear", and "Accessories".
          - name: name
            data_type: STRING
          - name: brand
            data_type: STRING
          - name: retail_price
            data_type: FLOAT64
          - name: department
            data_type: STRING
          - name: sku
            data_type: STRING
          - name: distribution_center_id
            data_type: INT64

      - name: users
        columns:
          - name: id
            data_type: INT64
          - name: first_name
            data_type: STRING
          - name: last_name
            data_type: STRING
          - name: email
            data_type: STRING
          - name: age
            data_type: INT64
          - name: gender
            data_type: STRING
          - name: state
            data_type: STRING
          - name: street_address
            data_type: STRING
          - name: postal_code
            data_type: STRING
          - name: city
            data_type: STRING
          - name: country
            data_type: STRING
          - name: latitude
            data_type: FLOAT64
          - name: longitude
            data_type: FLOAT64
          - name: traffic_source
            data_type: STRING
          - name: created_at
            data_type: TIMESTAMP